server:
  port: ${SERVICE_HTTP_PORT:4444}
  servlet:
    application-display-name: operation-test

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:operation}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-test-query: SELECT 1
      connectionTimeout: 20000
      idle-timeout: 20000
      minimum-idle: 3
      maximumPoolSize: 10
      keepalive-time: 5000
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate


  liquibase:
    change-log: classpath:/db/changelog/init.yaml
    enabled: true
    default-schema: public
    liquibase-schema: public

  data:
    mongodb:
      uri: mongodb://localhost:27017/operation
